### ISSUE TITLE
OSError: PortAudio library not found when using whisper-ctranslate2-0.1.7

### ISSUE THREAD

**Issue by FlippFuzz** [jordimas/whisper-ctranslate2#16]
```
time whisper-ctranslate2 --model large-v2 --language Japanese --task translate --verbose True --compute_type float32 --threads 4 --beam_size 1 --vad_filter True --vad_min_silence_duration_ms 2000 --output_dir output --output_format all -- audio.webm
Traceback (most recent call last):
  File "/home/jenkins/workspace/whisper-ctranslate2/venv/bin/whisper-ctranslate2", line 5, in <module>
    from src.whisper_ctranslate2.whisper_ctranslate2 import main
  File "/home/jenkins/workspace/whisper-ctranslate2/venv/lib/python3.10/site-packages/src/whisper_ctranslate2/whisper_ctranslate2.py", line 11, in <module>
    from .live import Live
  File "/home/jenkins/workspace/whisper-ctranslate2/venv/lib/python3.10/site-packages/src/whisper_ctranslate2/live.py", line 4, in <module>
    import sounddevice as sd
  File "/home/jenkins/workspace/whisper-ctranslate2/venv/lib/python3.10/site-packages/sounddevice.py", line 71, in <module>
    raise OSError('PortAudio library not found')
OSError: PortAudio library not found
```

---

Not sure if it helps, but this might be because I'm running this on a headless Ubuntu server, with no audio devices.
Works fine with whisper-ctranslate2-0.1.6

---

```
pip list
Package             Version
------------------- ---------
av                  10.0.0
Brotli              1.0.9
certifi             2022.12.7
cffi                1.15.1
charset-normalizer  3.1.0
coloredlogs         15.0.1
ctranslate2         3.10.3
faster-whisper      0.4.1
filelock            3.10.7
flatbuffers         23.3.3
huggingface-hub     0.13.3
humanfriendly       10.0
idna                3.4
mpmath              1.3.0
mutagen             1.46.0
numpy               1.24.2
onnxruntime         1.14.1
packaging           23.0
pip                 22.0.2
protobuf            4.22.1
pycparser           2.21
pycryptodomex       3.17
PyYAML              6.0
requests            2.28.2
setuptools          59.6.0
sounddevice         0.4.6
sympy               1.11.1
tokenizers          0.13.2
tqdm                4.65.0
typing_extensions   4.5.0
urllib3             1.26.15
websockets          11.0
whisper-ctranslate2 0.1.7
yt-dlp              2023.3.4
```

**Comment by jordimas** [comment]
Thanks for the report

Can you try to install libportaudio2 by running"sudo apt-get install libportaudio2" and try again?

Thanks

**Comment by FlippFuzz** [comment]
> Can you try to install libportaudio2 by running"sudo apt-get install libportaudio2" and try again?

Yes, that works.
It's a bit annoying to have to install additional non-python dependencies but isn't the end of the world.
Thanks!

**Comment by jordimas** [comment]
You are right. In the next version this dependency will only be needed when the functionality is used. Thanks
